# Generated by Django 5.1.7 on 2025-03-29 12:25

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('car', models.CharField(choices=[('Aston Martin DBX', 'Aston Martin DBX'), ('Range Rover Sport', 'Range Rover Sport'), ('Lamborghini Urus', 'Lamborghini Urus'), ('Ferrari SF90', 'Ferrari SF90'), ('Tesla Cybertruck', 'Tesla Cybertruck'), ('Rolls-Royce Cullinan', 'Rolls-Royce Cullinan'), ('Porsche 911 Turbo S', 'Porsche 911 Turbo S'), ('Bugatti Veyron', 'Bugatti Veyron'), ('Bentley Bentayga', 'Bentley Bentayga'), ('Mercedes G-Wagon', 'Mercedes G-Wagon')], default='Aston Martin DBX', max_length=100)),
                ('car_type', models.CharField(choices=[('SUV', 'SUV'), ('Sport', 'Sport'), ('Luxury', 'Luxury'), ('Electric', 'Electric')], default='SUV', max_length=50)),
                ('quantity', models.IntegerField()),
                ('order_status', models.CharField(choices=[('Pending', 'Pending'), ('In Transit', 'In Transit'), ('Delivered', 'Delivered')], default='Pending', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
