# Generated by Django 5.1.7 on 2025-03-29 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='car',
            field=models.CharField(choices=[('Aston Martin DBX', 'Aston Martin DBX'), ('Range Rover', 'Range Rover'), ('Lamborghini Urus', 'Lamborghini Urus'), ('Ferrari SF90', 'Ferrari SF90'), ('Tesla Cybertruck', 'Tesla Cybertruck'), ('Rolls-Royce Cullinan', 'Rolls-Royce Cullinan'), ('Porsche 911 Turbo S', 'Porsche 911 Turbo S'), ('Bugatti Veyron', 'Bugatti Veyron'), ('Bentley Bentayga', 'Bentley Bentayga'), ('Mercedes G-Wagon', 'Mercedes G-Wagon')], default='Aston Martin DBX', max_length=100),
        ),
    ]
